version: '3.8'

services:
  # Next.js Portfolio Application
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - portfolio-network
    # Uncomment if you need to debug
    # ports:
    #   - "3000:3000"

  # Caddy Reverse Proxy with Automatic HTTPS
  caddy:
    image: caddy:2-alpine
    container_name: portfolio-caddy
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - portfolio-network
    depends_on:
      - portfolio

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  portfolio-network:
    driver: bridge
